### ISSUE TITLE
Some fixes to make it work on 15.10 wily

### ISSUE THREAD

**Issue by hendrachristian** [Levantado/ngx_pagespeed-install-script#1]
There seems to be a slight change with the latest version.

My server setup:
DigitalOcean VPS
Ubuntu 15.10 wily
Nginx 1.9.6-1 (using
deb http://nginx.org/packages/mainline/ubuntu/ wily nginx
deb-src http://nginx.org/packages/mainline/ubuntu/ wily nginx)
NPS Version 1.9.32.10-7423

Line 37:
sed -i '61 a --add-module=../../ngx_pagespeed/ngx_pagespeed-master \' rules
this would not work because it will put it outside the {}. Fix:
sed -i '65 a --add-module=../../ngx_pagespeed/ngx_pagespeed-master \' rules

To fix PSOL not found, add:
After Line 37:
sed -i '58 a --with-cc-opt=" -D_GLIBCXX_USE_CXX11_ABI=0" \' rules
After Line 38:
sed -i '101 a --with-cc-opt=" -D_GLIBCXX_USE_CXX11_ABI=0" \' rules
(source: https://github.com/pagespeed/ngx_pagespeed/issues/327, http://servernesia.com/566/mempercepat-nginx-pagespeed-module/#comment-273)

**Comment by Levantado** [comment]
Add new version with auto chose what Ubuntu set, u can check.
