### ISSUE TITLE
error while overwriting some file 

### ISSUE THREAD

**Issue by pcompassion** [Levantado/ngx_pagespeed-install-script#3]
```
dpkg: error processing archive nginx_1.10.1-1~trusty_amd64.deb (--install):
 '/usr/share/nginx/html/index.html'의 덮어쓰기를 시도합니다. 이 파일은 nginx-common 1.4.6-1ubuntu3.5 패키지에도 들어있습니다
```

It translates to
It is trying to overwrite the index.html. This file is contained in nginx-common 1.4.6-1ubuntu3.5

I tried apt-get remove nginx-common but still same problem.

**Comment by Levantado** [comment]
You install on exist nginx, you need remove package all. And setup clean, or use new method, and set in another place.
