### ISSUE TITLE
Suggest the automated installer?

### ISSUE THREAD

**Issue by jeffkaufman** [Levantado/ngx_pagespeed-install-script#4]
ngx_pagespeed now has an [automated installer](https://developers.google.com/speed/pagespeed/module/build_ngx_pagespeed_from_source):

```
bash <(curl -f -L -sS https://ngxpagespeed.com/install) --nginx-version latest
```

or:

```
bash <(curl -f -L -sS https://ngxpagespeed.com/install) --help
```

Could you update your tutorial to suggest people use that instead?  It replaces many of the steps here, though not all of them.

**Comment by Levantado** [comment]
Thanks, Article rewrite.

**Comment by jeffkaufman** [comment]
Thanks!  Looks good!
